### ISSUE TITLE
Link not recognized when message not starting with it

### ISSUE THREAD

**Issue by Clevero** [phfn/yotbot#13]
Hello,

Currently, YotBot does not parse the link out of the message but expects it at first.
Example (This message is generated when the video link is shared through NewPipe)

```
【Glitch Hop】Chinese Man - I Got That Tune (Tha Trickaz Remix)
https://www.youtube.com/watch?v=_8dh_MzO_nU
```

**Comment by Clevero** [comment]
Results in:
![grafik](https://user-images.githubusercontent.com/6106081/116097833-d00b8880-a6aa-11eb-9022-725a18469883.png)

**Comment by phfn** [comment]
I like that you prefer to use YOTBot instead of:
a) using the NewPipe download function or 
b) the link that comes with the video

But anyway, with the latest patch links will be extracted. This also has the advantage that you can now send multiple links at the same time.

**Comment by phfn** [comment]
623fa16e5c75752fa8e3bc6e7a5169f08989089d
