### ISSUE TITLE
Tell the user if videos are not available in Germany.

### ISSUE THREAD

**Issue by phfn** [phfn/yotbot#5]
Some videos are not available in Germany. E.G. 
https://www.youtube.com/watch?v=CID-sYQNCew&feature=youtu.be
This should be displayed to the user.

**Comment by Clevero** [comment]
A workaround would be to use a proxy/vpn in order to download those videos.

To reduce costs, it would be possible to use free lists of proxy servers that are available on the internet

**Comment by phfn** [comment]
I may test something like this. But i'll only apply the changes if i find a way that is free and also stable. In any other case i would prefer to reply with something like "This Video is not avalible in Germany"
